version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: nginx_php
    ports:
      - "8090:80"
    volumes:
      - ./src:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:fpm
    container_name: php_fpm
    volumes:
      - ./src:/app
    env_file:
      - .env
    command: sh -c 'echo $FLAG > /flag.txt && php-fpm'
